title: Aidan Lorenz
logo: /assets/img/headshot.jpg
description: PhD candidate in mathematics and aspiring AI/ML Engineer/Data Scientist. aidanlorenz@gmail.com
show_downloads: false
theme: jekyll-theme-minimal
